name: Check executables
on: [push]

jobs:
  check-exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"
          "${GITHUB_WORKSPACE}/.github/script.sh"
